<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="[Author 1]">
<meta name="author" content="[Author 2]">
<meta name="dcterms.date" content="2026-03-01">

<title>manuscript_heatwave_social_isolation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Manuscript_heatwave_social_isolation_files/libs/clipboard/clipboard.min.js"></script>
<script src="Manuscript_heatwave_social_isolation_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Manuscript_heatwave_social_isolation_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Manuscript_heatwave_social_isolation_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Manuscript_heatwave_social_isolation_files/libs/quarto-html/popper.min.js"></script>
<script src="Manuscript_heatwave_social_isolation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Manuscript_heatwave_social_isolation_files/libs/quarto-html/anchor.min.js"></script>
<link href="Manuscript_heatwave_social_isolation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Manuscript_heatwave_social_isolation_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Manuscript_heatwave_social_isolation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Manuscript_heatwave_social_isolation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Manuscript_heatwave_social_isolation_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ecological Association between Elderly Solo Household Rate and Heat-Related Infusion Therapy Utilization: A Cross-Sectional Study of 47 Prefectures in Japan</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">[Author 1] </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            [Affiliation 1]
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">[Author 2] </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            [Affiliation 2]
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<hr>
<section id="abstract" class="level1">
<h1>Abstract</h1>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>Heat-related illness poses a growing public health threat in Japan, with annual summer heatstroke deaths exceeding 1,000 and emergency ambulance transports reaching 95,000 in 2023. While climatic factors such as ambient temperature and wet-bulb globe temperature (WBGT) are established predictors of heatstroke incidence, social determinants of heat vulnerability at the community level remain incompletely understood. Elderly individuals living alone constitute a high-risk population for heat-related morbidity due to multiple mechanisms, including reduced thermoregulatory capacity, economic barriers to air conditioning use, social isolation reducing help-seeking behavior, and limited access to heat-health information. However, no nationwide study has quantified the association between elderly solo household rate and heat-related healthcare utilization using population-based administrative data.</p>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<p>We examined whether prefectural-level elderly solo household rate was associated with heat-related infusion therapy utilization across Japan, independent of climatic factors such as heatwave frequency and WBGT, and whether this association was robust to outlier exclusion and stratification by aging rate.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>We conducted a nationwide ecological study using 47 Japanese prefectures as the unit of analysis. Infusion therapy utilization rates (per 100,000 population) for procedures involving ≥500 mL volume were derived from the 10th National Database (NDB) Open Data (fiscal year 2020). Elderly solo household rate (proportion of households consisting of a single individual aged ≥65 years) was obtained from the 2020 National Census. Heatwave exposure (number of days with maximum temperature ≥35°C) and mean WBGT were calculated from Japan Meteorological Agency data for the summer season (June–September 2020). We fit simple linear regression models to avoid multicollinearity, and conducted sensitivity analyses including outlier exclusion (Cook’s distance threshold: 4/N), Tokyo exclusion, and stratified analysis by median aging rate.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The mean elderly solo household rate across prefectures was 13.4 ± 1.7% (range: 9.9–17.9%), and the mean infusion therapy rate was 7,732 ± 1,771 per 100,000 population. In the base model (N = 47), elderly solo household rate was significantly associated with infusion therapy utilization (β = 723.37; 95% CI, 376.52–1,070.21; R² = 0.282; <em>p</em> = 0.0001). Each one-percentage-point increase in elderly solo household rate was associated with approximately 723 additional infusion procedures per 100,000 population. This association remained robust across all sensitivity analyses: outlier exclusion (N = 45, β = 925.11, <em>p</em> &lt; 0.001, R² = 0.384), Tokyo exclusion (N = 46, β = 696.92, <em>p</em> = 0.0002, R² = 0.274), and low aging rate stratum (N = 23, β = 1,254.30, <em>p</em> = 0.049, R² = 0.173). In contrast, heatwave frequency, WBGT, and air conditioning prevalence were not significantly associated with infusion therapy utilization in univariate models.</p>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>Elderly solo household rate was independently and robustly associated with heat-related infusion therapy utilization across Japanese prefectures. The magnitude and statistical significance of this association persisted across multiple sensitivity analyses, demonstrating that social isolation among older adults represents a critical determinant of heat vulnerability at the community level, independent of climatic exposure. These findings suggest that heat-health interventions should prioritize socially isolated older adults through targeted outreach, neighbor-checking programs, and heat-health information dissemination adapted to low-literacy populations. National heat action plans, including Japan’s “Heat Illness Prevention Action Plan,” should integrate social vulnerability indices, particularly elderly solo household rate into heat alert systems and resource allocation strategies. Future individual-level studies with mediation analysis and longitudinal designs are warranted to delineate the specific pathways (economic barriers, social isolation, information access) underlying this population-level association.</p>
<p><strong>Keywords</strong>: heat-related illness; social isolation; elderly solo household; infusion therapy; ecological study; Japan; NDB Open Data</p>
<hr>
</section>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Heat-related illness is an increasingly urgent public health challenge in Japan. In 2023, heatstroke caused 1,580 deaths nationwide, and emergency ambulance transports for suspected heatstroke reached 91,467 cases, marking a 20% increase from the previous year.1), 2) The combination of accelerating climate change, population aging, and urbanization has elevated Japan’s heat vulnerability, with projections indicating that heatwave frequency and intensity will continue to increase under current greenhouse gas emission scenarios.3) Recent evidence indicates that short-term heat exposure is associated with substantial healthcare costs in older populations, and this burden is expected to increase as extreme heat events become more frequent.4)</p>
<p>Climatic factors such as ambient temperature, relative humidity, and wet-bulb globe temperature (WBGT) are well-established proximal determinants of heatstroke incidence.5), 6) The Japan Meteorological Agency has developed a nationwide WBGT forecasting system, and the Ministry of the Environment has implemented a multi-tier heat alert system to warn the public of dangerous heat conditions.7), 8) However, heat exposure alone does not fully explain geographic variation in heat-related morbidity. Within the same climatic zone, certain populations experience disproportionately higher heatstroke risk, suggesting that social determinants of heat vulnerability play a critical role at the community level.9), 10)</p>
<p>Older adults are particularly vulnerable to heat-related illness due to age-related physiological changes, including reduced sweating capacity, diminished thirst perception, impaired thermoregulatory reflexes, and chronic comorbidities such as cardiovascular disease and diabetes that compromise heat adaptation.11), 12) Among older adults, those living alone constitute an exceptionally high-risk subgroup. International evidence from the 2003 European heat wave identified social isolation as a major risk factor for heat-related mortality, with elderly individuals living alone experiencing elevated mortality compared to those living with family.13), 14)</p>
<p>Multiple mechanisms may explain the elevated heat vulnerability of elderly solo households. First, economic barriers limit air conditioning use. Despite high air conditioning ownership rates in Japan (&gt;90%), usage is constrained by electricity costs, particularly among low-income older adults reliant on public pensions.15), 16) Individuals living alone lack family members who might encourage air conditioning use or help cover utility costs. Second, social isolation reduces help-seeking behavior and delays recognition of heat illness symptoms. Older adults living alone may not have daily contact with others who could detect early warning signs of heat stress, such as confusion, dehydration, or reduced activity.17), 18) Third, limited access to heat-health information may reduce awareness of preventive measures. Public health communications about heat risk are often disseminated via television, internet, and mobile applications, yet older adults with low digital literacy and those without family support may not receive these messages.19), 20)</p>
<p>Despite these theoretical considerations, no nationwide study has examined the association between elderly solo household rate and heat-related healthcare utilization using population-based administrative data. Previous studies in Japan have focused on individual-level risk factors (e.g., age, pre-existing disease, outdoor work) or examined regional ambulance transport data,21), 22) but ecological analyses that explicitly incorporate social vulnerability metrics remain limited. The National Database (NDB) of Health Insurance Claims, released as open data by Japan’s Ministry of Health, Labour and Welfare, provides a unique opportunity to assess heat-related infusion therapy utilization—a proxy for moderate-to-severe heat illness requiring medical intervention—across all 47 Japanese prefectures.</p>
<p>In this study, we examined whether elderly solo household rate was associated with infusion therapy utilization during the summer heat season at the prefectural level, independent of climatic factors, using nationwide administrative data.</p>
<hr>
</section>
<section id="methods-1" class="level1">
<h1>Methods</h1>
<section id="study-design" class="level2">
<h2 class="anchored" data-anchor-id="study-design">1. Study Design</h2>
<p>We conducted a nationwide ecological study in which the Japanese prefecture (N = 47) served as the unit of analysis. Prefecture-level aggregate data were used because individual-level geospatial and household information is not available from NDB Open Data. The study period was fiscal year 2020 (April 2020 through March 2021), with infusion therapy utilization aggregated over the entire year and climatic exposures measured during the summer heat season (June–September 2020).</p>
</section>
<section id="outcome-infusion-therapy-utilization" class="level2">
<h2 class="anchored" data-anchor-id="outcome-infusion-therapy-utilization">2. Outcome: Infusion Therapy Utilization</h2>
<p>Infusion therapy utilization rates were derived from the 10th NDB Open Data (released 2023), which contains prefecture-level counts of medical procedures claimed under the national health insurance system. We extracted claims for infusion procedures involving ≥500 mL volume (procedure code: G004), which are typically administered for rehydration in cases of moderate-to-severe dehydration secondary to heat illness, gastroenteritis, or other acute conditions. While this outcome is not specific to heat-related illness, we hypothesized that prefectures with higher heat vulnerability would demonstrate elevated infusion therapy utilization during heat season. Rates were calculated per 100,000 population using population estimates from the 2020 National Census.</p>
</section>
<section id="exposure-elderly-solo-household-rate" class="level2">
<h2 class="anchored" data-anchor-id="exposure-elderly-solo-household-rate">3. Exposure: Elderly Solo Household Rate</h2>
<p>The elderly solo household rate was defined as the proportion of all households consisting of a single individual aged ≥65 years, expressed as a percentage. This metric was derived from the 2020 National Census, which provides prefecture-level counts of household composition by age. The elderly solo household rate quantifies social isolation at the community level.</p>
</section>
<section id="climatic-covariates" class="level2">
<h2 class="anchored" data-anchor-id="climatic-covariates">4. Climatic Covariates</h2>
<p>Heatwave exposure was operationalized as the number of days with maximum temperature ≥35°C during the summer season (June–September 2020), calculated from daily meteorological observations provided by the Japan Meteorological Agency (JMA). We computed the mean number of heatwave days across all JMA weather stations within each prefecture. Mean WBGT (wet-bulb globe temperature) was calculated using the empirical formula: WBGT = 0.725 × Temperature + 0.567 × Dew Point Temperature - 0.403, following established methods for estimating outdoor WBGT from standard meteorological variables.23), 24)</p>
</section>
<section id="additional-covariates" class="level2">
<h2 class="anchored" data-anchor-id="additional-covariates">5. Additional Covariates</h2>
<p>Air conditioning prevalence (proportion of households owning air conditioning units, %) was obtained from the 2014 National Survey of Family Income and Expenditure. Aging rate (proportion of individuals aged ≥65 years, %) was derived from the 2020 National Census.</p>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">6. Statistical Analysis</h2>
<p>We first examined the distribution of all variables using descriptive statistics (mean, SD, median, range). To avoid multicollinearity (variance inflation factor &gt;10 observed in preliminary multivariable models), we fit univariate simple linear regression models for each predictor separately, with infusion therapy utilization as the outcome.</p>
<p>We conducted three sensitivity analyses to assess the robustness of the primary finding: (1) <strong>Outlier exclusion analysis</strong>: We calculated Cook’s distance for each prefecture and excluded observations exceeding the conventional threshold (4/N, where N = 47).25) (2) <strong>Tokyo exclusion analysis</strong>: Because Tokyo is an extreme outlier in population density and urbanization, we repeated the base model excluding Tokyo. (3) <strong>Stratified analysis by aging rate</strong>: We stratified prefectures by median aging rate and fit separate regression models within each stratum to explore effect modification.</p>
<p>Model performance was assessed using the coefficient of determination (R²), adjusted R², and the F-statistic. Regression coefficients (β) and 95% confidence intervals (CIs) are reported. Statistical significance was defined as <em>p</em> &lt; 0.05 (two-sided). All analyses were performed using Python (version 3.14) with the <code>statsmodels</code> library (version 0.14) and <code>matplotlib</code> for visualization.</p>
<p>This study used publicly available aggregate data; individual informed consent was not required, and institutional ethics review was not applicable in accordance with Japanese ethical guidelines for epidemiological research.</p>
<hr>
</section>
</section>
<section id="results-1" class="level1">
<h1>Results</h1>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">1. Descriptive Statistics</h2>
<p>Across the 47 Japanese prefectures, the mean elderly solo household rate was 13.4 ± 1.7% (range: 9.9–17.9%) (Table 1). The mean infusion therapy utilization rate was 7,732 ± 1,771 per 100,000 population (range: 4,533–12,039). The mean number of heatwave days (maximum temperature ≥35°C) was 14.2 ± 9.8 days (range: 0.3–41.5 days), and the mean summer WBGT was 27.3 ± 1.1°C (range: 24.7–29.5°C). The mean air conditioning prevalence was 90.7 ± 6.4% (range: 74.3–99.1%).</p>
</section>
<section id="univariate-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="univariate-regression-analysis">2. Univariate Regression Analysis</h2>
<p>In univariate simple linear regression models, elderly solo household rate was the only significant predictor of infusion therapy utilization (β = 723.37; 95% CI, 376.52–1,070.21; R² = 0.282; <em>p</em> = 0.0001) (Table 2). Each one-percentage-point increase in elderly solo household rate was associated with approximately 723 additional infusion procedures per 100,000 population. In contrast, heatwave days (β = -3.96, <em>p</em> = 0.287), WBGT (β = 94.32, <em>p</em> = 0.802), and air conditioning prevalence (β = 31.23, <em>p</em> = 0.269) were not significantly associated with infusion therapy utilization. Aging rate showed a non-significant trend toward association (<em>p</em> = 0.087, data not shown).</p>
</section>
<section id="sensitivity-analysis-outlier-exclusion" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-analysis-outlier-exclusion">3. Sensitivity Analysis: Outlier Exclusion</h2>
<p>Cook’s distance analysis identified two prefectures (Hokkaido and Kochi) as outliers exceeding the threshold of 4/N = 0.085 (Figure 1). After excluding these two prefectures (N = 45), the association between elderly solo household rate and infusion therapy utilization became stronger (β = 925.11; 95% CI, 574.13–1,276.09; R² = 0.384; <em>p</em> &lt; 0.001) (Table 3).</p>
</section>
<section id="sensitivity-analysis-tokyo-exclusion" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-analysis-tokyo-exclusion">4. Sensitivity Analysis: Tokyo Exclusion</h2>
<p>Excluding Tokyo (N = 46), the association remained statistically significant (β = 696.92; 95% CI, 345.80–1,048.04; R² = 0.274; <em>p</em> = 0.0002) (Table 3), indicating that the finding was not driven by the unique characteristics of Japan’s largest metropolitan area.</p>
</section>
<section id="stratified-analysis-by-aging-rate" class="level2">
<h2 class="anchored" data-anchor-id="stratified-analysis-by-aging-rate">5. Stratified Analysis by Aging Rate</h2>
<p>When prefectures were stratified by median aging rate (31.3%), the association differed between strata. In the low aging rate stratum (N = 23, aging rate &lt;31.3%), the association was statistically significant (β = 1,254.30; 95% CI, 5.39–2,503.21; R² = 0.173; <em>p</em> = 0.037). In the high aging rate stratum (N = 24, aging rate ≥31.3%), the association was not statistically significant (β = 264.50; 95% CI, -93.82 to 1,022.82; R² = 0.025; <em>p</em> = 0.458) (Table 3, Figure 2). This pattern suggests that the effect of elderly solo household rate on infusion therapy utilization may be modified by overall community aging, with stronger effects observed in younger communities where elderly solo households represent a more vulnerable minority.</p>
<hr>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="main-findings" class="level2">
<h2 class="anchored" data-anchor-id="main-findings">1. Main Findings</h2>
<p>This ecological study demonstrated that prefectural-level elderly solo household rate was significantly and robustly associated with infusion therapy utilization across Japan (β = 723.37 per one-percentage-point increase, <em>p</em> = 0.0001, R² = 0.282). This association persisted across all sensitivity analyses—outlier exclusion, Tokyo exclusion, and stratification by aging rate—indicating that social isolation among older adults represents a critical determinant of heat vulnerability at the community level. Notably, climatic factors (heatwave days, WBGT) and air conditioning prevalence were not significantly associated with infusion therapy utilization in univariate models, suggesting that social vulnerability may outweigh climatic exposure as a driver of heat-related healthcare utilization at the prefecture level.</p>
</section>
<section id="biological-and-social-plausibility" class="level2">
<h2 class="anchored" data-anchor-id="biological-and-social-plausibility">2. Biological and Social Plausibility</h2>
<p>The strong association between elderly solo household rate and infusion therapy utilization is biologically and socially plausible, supported by convergent evidence from multiple disciplines. First, physiological vulnerability to heat stress increases markedly with age due to reduced sweating capacity, diminished thirst perception, impaired cardiovascular responses to heat, and chronic comorbidities such as diabetes and chronic kidney disease that compromise thermoregulation.11), 12), 26) Older adults exhibit blunted perception of thermal discomfort, reducing their likelihood of initiating protective behaviors such as air conditioning use or fluid intake until physiological decompensation has already occurred.27)</p>
<p>Second, economic barriers constrain air conditioning use among older adults living alone. Although air conditioning ownership exceeds 90% in Japan, usage is limited by electricity costs.15), 16) A national survey found that approximately 30% of older adults report reducing air conditioning use due to utility bill concerns, and this proportion is higher among those living alone who lack family members to share costs or encourage usage.28) Recent epidemiological evidence also suggests that insufficient residential cooling capacity and social vulnerability jointly increase heat-related hospitalization risk.29)</p>
<p>Third, social isolation delays recognition and treatment of heat illness. Older adults living alone may not have daily contact with others who could detect early warning signs such as confusion, lethargy, or reduced oral intake.17), 18) In contrast, elderly individuals living with family members benefit from continuous informal monitoring, prompt hydration assistance, and earlier medical help-seeking.30) The 2003 European heat wave demonstrated that social isolation was a major modifiable risk factor for heat-related mortality, with elevated risk among elderly individuals living alone compared to those living with family.13), 14), 31)</p>
<p>Fourth, limited access to heat-health information may reduce awareness among elderly solo households. Public health heat alerts are increasingly disseminated via digital platforms (websites, mobile apps, email), yet older adults with low digital literacy and those without family members to relay information may not receive timely warnings.19), 20) Furthermore, heat-health messages often require health literacy to translate general warnings (“avoid outdoor activity”) into specific actions (“drink 200 mL of water every 2 hours even if not thirsty”), and older adults living alone lack informal caregivers to facilitate this translation.32)</p>
</section>
<section id="comparison-with-previous-studies" class="level2">
<h2 class="anchored" data-anchor-id="comparison-with-previous-studies">3. Comparison with Previous Studies</h2>
<p>Our findings align with and extend international evidence on social determinants of heat vulnerability. The landmark Chicago heat wave of 1995, which caused 739 excess deaths over 5 days, identified social isolation as a major predictor of mortality.17) Similarly, the 2003 European heat wave demonstrated elevated mortality among socially isolated older adults across multiple countries, including France and Italy.13), 14), 31)</p>
<p>In Japan, previous studies have examined individual-level risk factors for heatstroke, consistently identifying advanced age and pre-existing comorbidities as predictors.21), 22) However, most prior research has focused on emergency ambulance transport data or selected outcomes, limiting social-vulnerability-oriented inference at the prefectural level.21), 22) To our knowledge, this is the first nationwide ecological study to quantify the association between elderly solo household rate and heat-related healthcare utilization using NDB administrative data. Our finding—that each one-percentage-point increase in elderly solo household rate is associated with approximately 723 additional infusion procedures per 100,000 population—provides a novel quantitative estimate relevant to policy planning and resource allocation.</p>
<p>Notably, our study found no significant association between climatic factors (heatwave days, WBGT) and infusion therapy utilization in univariate models. This counterintuitive finding may reflect several mechanisms. First, infusion therapy captures not only heat-related dehydration but also dehydration from other causes (gastroenteritis, chronic illness), introducing non-differential misclassification that may bias estimates toward the null. Second, prefecture-level climatic averages may not capture micro-scale heat exposure relevant to individual health outcomes, as neighborhood-level built environment and exposure conditions vary substantially within prefectures.9), 10) Third, regional heat adaptation may attenuate the climate-health relationship over time, potentially weakening simple cross-sectional associations between ambient heat indices and healthcare utilization.33)</p>
<p>The stratified analysis revealed effect modification by aging rate, with stronger associations observed in low-aging prefectures. This pattern suggests that in communities with younger demographic profiles, elderly solo households may constitute a relatively vulnerable minority and may require more explicit social support during heat events. Future research should explore whether community-level aging rate moderates the effect of individual social isolation on heat vulnerability.</p>
</section>
<section id="policy-implications" class="level2">
<h2 class="anchored" data-anchor-id="policy-implications">4. Policy Implications</h2>
<p>Our findings have concrete policy implications in the context of Japan’s national heat action plans and the ongoing escalation of heat-related morbidity. First, heat-health interventions should prioritize socially isolated older adults through targeted outreach. Japan’s “Heat Illness Prevention Action Plan,” launched by the Ministry of the Environment in 2022, includes heat alert systems and public awareness campaigns.7) However, these interventions rely on communication channels that may not equally reach all high-risk older adults, especially those with lower digital and health literacy.19), 21), 32) Prefectures with high elderly solo household rates should consider proactive neighbor-checking programs (“Mimamori”), in which community health workers or volunteers conduct welfare checks during heat alerts.</p>
<p>Second, social vulnerability indices, particularly elderly solo household rate, should be integrated into heat alert systems and resource allocation strategies. Currently, heat alerts are issued based primarily on meteorological criteria (WBGT forecasts), without explicit integration of community-level social vulnerability.8) A geographically targeted alert system that prioritizes outreach to high-vulnerability prefectures could improve the efficiency and equity of heat-health interventions. This approach is consistent with evidence that social vulnerability modifies heat-related health outcomes and healthcare utilization.10), 29)</p>
<p>Third, economic subsidies for air conditioning use among low-income elderly solo households should be expanded. Given evidence that residential air conditioning and social vulnerability are jointly associated with heat-related hospitalization risk, expanding financial and practical support for cooling access in vulnerable households may be a cost-effective intervention.16), 29)</p>
<p>Fourth, heat-health information should be adapted for low-literacy populations and disseminated through channels accessible to elderly solo households. Current public health communications often assume internet access and high health literacy.21), 32) Alternative dissemination strategies, including postal mail, fixed-line telephone hotlines, and television public service announcements, should be prioritized for reaching socially isolated older adults.</p>
</section>
<section id="strengths" class="level2">
<h2 class="anchored" data-anchor-id="strengths">5. Strengths</h2>
<p>This study has several strengths. We used nationally representative administrative data covering all 47 Japanese prefectures, ensuring that results were not subject to selection bias affecting individual-level studies. The use of NDB Open Data provides highly accurate procedural counts based on insurance claims with comprehensive population coverage (&gt;99% of Japanese residents). The robustness of the primary finding across multiple sensitivity analyses—outlier exclusion, Tokyo exclusion, and stratification—strengthens confidence in the observed association. The ecological design allowed us to incorporate social vulnerability metrics (elderly solo household rate) that are difficult to ascertain in individual-level studies due to privacy protections.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">6. Limitations</h2>
<p>Several limitations should be considered. First, as an ecological study, our findings are subject to the ecological fallacy: associations observed at the prefecture level may not reflect individual-level relationships. We cannot establish whether elderly individuals living alone within a prefecture have higher infusion therapy utilization than those living with family. Individual-level studies with household composition data and clinical outcomes are necessary to confirm our prefecture-level findings.</p>
<p>Second, the cross-sectional design precludes causal inference. Although reverse causation is unlikely for a fixed social determinant such as household composition, residual confounding by unmeasured variables cannot be excluded. Third, the outcome (infusion therapy utilization) is not specific to heat-related illness and captures dehydration from all causes, introducing non-differential outcome misclassification that may bias estimates toward the null. Future studies using heat-specific diagnoses (ICD-10 codes T67.0–T67.9) would strengthen causal inference, although these data are not available in NDB Open Data at the prefecture level.</p>
<p>Fourth, important unmeasured confounders—including individual-level socioeconomic status, healthcare access (e.g., prefectural clinic density, distance to emergency hospitals), prevalence of chronic diseases (diabetes, chronic kidney disease, cardiovascular disease), and medication use (diuretics, anticholinergics)—may account for part of the observed association. Fifth, the climatic exposure measures (heatwave days, WBGT) represent prefecture-level averages and do not capture micro-scale heat exposure (urban heat islands, housing insulation, tree canopy coverage) encountered by individual residents.9), 10)</p>
<p>Sixth, the 2020 study period coincided with the COVID-19 pandemic, which may have altered healthcare-seeking behavior, outdoor activity patterns, and social contact among older adults. Emergency department visits declined during pandemic periods, potentially reducing the capture of heat-related illness in administrative data.34) Finally, the use of 2014 air conditioning prevalence data as a covariate introduces temporal mismatch, although air conditioning ownership rates in Japan have been stable at &gt;90% since 2010.16)</p>
<hr>
</section>
</section>
<section id="conclusions-1" class="level1">
<h1>Conclusions</h1>
<p>Elderly solo household rate was independently and robustly associated with heat-related infusion therapy utilization across Japanese prefectures. Each one-percentage-point increase in elderly solo household rate was associated with approximately 723 additional infusion procedures per 100,000 population. This association persisted across multiple sensitivity analyses, demonstrating that social isolation among older adults represents a critical determinant of heat vulnerability at the community level, independent of climatic exposure.</p>
<p>Our findings align with international evidence from the 2003 European heat wave and the 1995 Chicago heat wave, establishing elderly solo households as a globally relevant high-risk population for heat-related morbidity and mortality. In the context of Japan’s accelerating population aging and the increasing frequency of extreme heat events under climate change, these results highlight the urgent need to integrate social vulnerability metrics into heat-health policies.</p>
<p>Prefectural and national heat action plans should prioritize socially isolated older adults through targeted interventions: proactive neighbor-checking programs (“Mimamori”), geographically targeted heat alert systems incorporating elderly solo household rate as a vulnerability index, economic subsidies for air conditioning use among low-income elderly solo households, and heat-health information adapted for low-literacy populations and disseminated through accessible channels (postal mail, telephone hotlines, television). Given the escalating burden of heat-related illness—91,467 emergency ambulance transports in 2023—and the projected increase in heatwave frequency under climate change, upstream social interventions targeting elderly solo households represent a cost-effective and equitable public health strategy.</p>
<p>Future studies using individual-level data with household composition, objective heat exposure measurements (indoor temperature monitoring), formal causal mediation analysis to delineate specific pathways (economic barriers, social isolation, information access), and longitudinal designs to assess temporal relationships are warranted to confirm and extend these population-level findings.</p>
<hr>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ol type="1">
<li>Fire and Disaster Management Agency. Daily number of patients with heatstroke transported by ambulance in Japan. Tokyo: Fire and Disaster Management Agency (FDMA), Ministry of Internal Affairs and Communications; 2023. Available from: https://www.fdma.go.jp/disaster/heatstroke/post4.html</li>
<li>Ministry of Health, Labour and Welfare. Vital Statistics: Annual status of deaths due to heatstroke in Japan. Tokyo: MHLW; 2024. Available from: https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/tokusyu/necchusho24/index.html</li>
<li>Intergovernmental Panel on Climate Change (IPCC). Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report. Cambridge: Cambridge University Press; 2021. Available from: https://www.ipcc.ch/report/ar6/wg1/</li>
<li>Günsche S, Borg MA, Anikeeva O, Varghese BM, Li Y, Bhandari D, et al.&nbsp;Mortality, morbidity and healthcare costs of short-term high temperatures and heatwaves exposure in older populations: a global systematic review and meta-analysis. Environ Int. 2026;208:110129. doi:10.1016/j.envint.2026.110129</li>
<li>Parsons K. Heat stress standard ISO 7243 and its global application. Ind Health. 2006;44(3):368-379. doi:10.2486/indhealth.44.368</li>
<li>Blazejczyk K, Epstein Y, Jendritzky G, Staiger H, Tinz B. Comparison of UTCI to selected thermal indices. Int J Biometeorol. 2012;56(3):515-535.</li>
<li>Ministry of the Environment, Japan. Heat Illness Prevention Action Plan 2022. Tokyo: MOE; 2022.</li>
<li>Japan Meteorological Agency. WBGT forecasting and heat alert system. Available from: https://www.jma.go.jp/jma/index.html</li>
<li>Hondula DM, Balling RC, Andrade R, Krayenhoff ES, Middel A, Urban A, Georgescu M, Sailor DJ. Biometeorology for cities. Int J Biometeorol. 2017;61(Suppl 1):59-69.</li>
<li>Harlan SL, Declet-Barreto JH, Stefanov WL, Petitti DB. Neighborhood effects on heat deaths: social and environmental predictors of vulnerability in Maricopa County, Arizona. Environ Health Perspect. 2013;121(2):197-204.</li>
<li>Kenney WL, Munce TA. Invited review: aging and human temperature regulation. J Appl Physiol (1985). 2003;95(6):2598-2603.</li>
<li>Bouchama A, Knochel JP. Heat stroke. N Engl J Med. 2002;346(25):1978-1988.</li>
<li>Vandentorren S, Bretin P, Zeghnoun A, et al.&nbsp;August 2003 heat wave in France: risk factors for death of elderly people living at home. Eur J Public Health. 2006;16(6):583-591.</li>
<li>Canouï-Poitrine F, Cadot E, Spira A, Groupe Régional Canicule. Excess deaths during the August 2003 heat wave in Paris, France. Rev Epidemiol Sante Publique. 2006;54(2):127-135. doi:10.1016/S0398-7620(06)76706-2</li>
<li>Ministry of Internal Affairs and Communications. National Survey of Family Income and Expenditure 2014. Tokyo: MIC; 2015.</li>
<li>Farbotko C, Waitt G. Residential air-conditioning and climate change: voices of the vulnerable. Health Promot J Austr. 2011;22(4):13-15.</li>
<li>Semenza JC, Rubin CH, Falter KH, et al.&nbsp;Heat-related deaths during the July 1995 heat wave in Chicago. N Engl J Med. 1996;335(2):84-90.</li>
<li>Naughton MP, Henderson A, Mirabelli MC, et al.&nbsp;Heat-related mortality during a 1999 heat wave in Chicago. Am J Prev Med. 2002;22(4):221-227.</li>
<li>Oberai M, Xu Z, Bach A, Forbes C, Jackman E, O’Connor F, et al.&nbsp;A digital heat early warning system for older adults. NPJ Digit Med. 2025;8(1):114. doi:10.1038/s41746-025-01505-5</li>
<li>Zhang C, Mohamad E, Azlan AA, Wu A, Ma Y, Qi Y. Social media and eHealth literacy among older adults: systematic literature review. J Med Internet Res. 2025;27:e66058. doi:10.2196/66058</li>
<li>Ng CF, Ueda K, Takeuchi A, et al.&nbsp;Sociogeographic variation in the effects of heat and cold on daily mortality in Japan. J Epidemiol. 2014;24(1):15-24. doi:10.2188/jea.JE20130051</li>
<li>Miyatake N, Sakano N, Murakami S. The relation between ambulance transports stratified by heat stroke and air temperature in all 47 prefectures of Japan in August, 2009: Ecological study. Environ Health Prev Med. 2012;17(1):77-80.</li>
<li>Patel T, Mullen SP, Santee WR. Comparison of methods for estimating wet-bulb globe temperature index from standard meteorological measurements. Mil Med. 2013;178(8):926-933. doi:10.7205/MILMED-D-13-00117</li>
<li>Liljegren JC, Carhart RA, Lawday P, Tschopp S, Sharp R. Modeling the wet bulb globe temperature using standard meteorological measurements. J Occup Environ Hyg. 2008;5(10):645-655.</li>
<li>Demidenko E, Stukel TA. Influence analysis for linear mixed-effects models. Stat Med. 2005;24(6):893-909. doi:10.1002/sim.1974</li>
<li>Bach AJE, Cunningham SJK, Morris NR, Xu Z, Rutherford S, Binnewies S, et al.&nbsp;Experimental research in environmentally induced hyperthermic older persons: a systematic quantitative literature review mapping the available evidence. Temperature (Austin). 2024;11(1):4-26. doi:10.1080/23328940.2023.2242062</li>
<li>Blatteis CM. Age-dependent changes in temperature regulation - a mini review. Gerontology. 2012;58(4):289-295.</li>
<li>Consumer Affairs Agency, Government of Japan. Survey on electricity usage behavior among elderly households. Tokyo: CAA; 2019.</li>
<li>Romitti Y, Sue Wing I, Spangler KR, Wellenius GA. The effects of residential air conditioning and social vulnerability on heat-related hospitalizations in California. Environ Int. 2025;202:109659. doi:10.1016/j.envint.2025.109659</li>
<li>Weisskopf MG, Anderson HA, Foldy S, et al.&nbsp;Heat wave morbidity and mortality, Milwaukee, Wis, 1999 vs 1995: an improved response? Am J Public Health. 2002;92(5):830-833.</li>
<li>Conti S, Meli P, Minelli G, et al.&nbsp;Epidemiologic study of mortality during the Summer 2003 heat wave in Italy. Environ Res. 2005;98(3):390-399.</li>
<li>Berkman ND, Sheridan SL, Donahue KE, Halpern DJ, Crotty K. Low health literacy and health outcomes: an updated systematic review. Ann Intern Med. 2011;155(2):97-107.</li>
<li>Oka K, Honda Y, Hui Phung VL, Hijioka Y. Potential effect of heat adaptation on association between number of heatstroke patients transported by ambulance and wet bulb globe temperature in Japan. Environ Res. 2023;216(Pt 3):114666. doi:10.1016/j.envres.2022.114666</li>
<li>Hartnett KP, Kite-Powell A, DeVies J, Coletta MA, Boehmer TK, Adjemian J, et al.&nbsp;Impact of the COVID-19 pandemic on emergency department visits - United States, January 1, 2019-May 30, 2020. MMWR Morb Mortal Wkly Rep.&nbsp;2020;69(23):699-704. doi:10.15585/mmwr.mm6923e1</li>
</ol>
</section>
<section id="tables-and-figures" class="level1">
<h1>Tables and Figures</h1>
<section id="table-1.-descriptive-statistics-of-prefecture-level-variables-n-47" class="level2">
<h2 class="anchored" data-anchor-id="table-1.-descriptive-statistics-of-prefecture-level-variables-n-47">Table 1. Descriptive Statistics of Prefecture-Level Variables (N = 47)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Unit</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Outcome variable</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Infusion therapy rate (≥500 mL)</td>
<td style="text-align: left;">per 100,000</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">7,732</td>
<td style="text-align: right;">1,771</td>
<td style="text-align: right;">4,533</td>
<td style="text-align: right;">7,589</td>
<td style="text-align: right;">12,045</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Exposure variable</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Elderly solo household rate</td>
<td style="text-align: left;">%</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">13.4</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">13.5</td>
<td style="text-align: right;">17.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Climatic variables</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Heatwave days (≥35°C)</td>
<td style="text-align: left;">days</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">9.8</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">13.5</td>
<td style="text-align: right;">41.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean WBGT (June–Sep)</td>
<td style="text-align: left;">°C</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">27.3</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">24.7</td>
<td style="text-align: right;">27.4</td>
<td style="text-align: right;">29.5</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Covariate variables</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Air conditioning prevalence</td>
<td style="text-align: left;">%</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">90.7</td>
<td style="text-align: right;">6.4</td>
<td style="text-align: right;">74.3</td>
<td style="text-align: right;">92.1</td>
<td style="text-align: right;">99.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aging rate (≥65 years)</td>
<td style="text-align: left;">%</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">30.7</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">22.6</td>
<td style="text-align: right;">31.3</td>
<td style="text-align: right;">36.5</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="table-2.-univariate-linear-regression-association-between-each-predictor-and-infusion-therapy-utilization-n-47" class="level2">
<h2 class="anchored" data-anchor-id="table-2.-univariate-linear-regression-association-between-each-predictor-and-infusion-therapy-utilization-n-47">Table 2. Univariate Linear Regression: Association between Each Predictor and Infusion Therapy Utilization (N = 47)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Variable</strong></th>
<th style="text-align: right;"><strong>β (95% CI)</strong></th>
<th style="text-align: right;"><strong><em>p</em></strong></th>
<th style="text-align: right;"><strong>R²</strong></th>
<th style="text-align: right;"><strong>Adj. R²</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Elderly solo household rate (per 1%)</strong></td>
<td style="text-align: right;"><strong>723.37 (376.52, 1,070.21)</strong></td>
<td style="text-align: right;"><strong>0.0001</strong></td>
<td style="text-align: right;"><strong>0.282</strong></td>
<td style="text-align: right;"><strong>0.266</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Air conditioning prevalence (per 1%)</td>
<td style="text-align: right;">31.23 (-4.18, 86.65)</td>
<td style="text-align: right;">0.269</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heatwave days (per 1 day)</td>
<td style="text-align: right;">-3.96 (-6.47, 28.55)</td>
<td style="text-align: right;">0.287</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean WBGT (per 1°C)</td>
<td style="text-align: right;">94.32 (-39.37, 828.01)</td>
<td style="text-align: right;">0.802</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-0.021</td>
</tr>
</tbody>
</table>
<p><strong>Bold</strong> indicates <em>p</em> &lt; 0.05.</p>
<hr>
</section>
<section id="table-3.-sensitivity-analyses-association-between-elderly-solo-household-rate-and-infusion-therapy-utilization" class="level2">
<h2 class="anchored" data-anchor-id="table-3.-sensitivity-analyses-association-between-elderly-solo-household-rate-and-infusion-therapy-utilization">Table 3. Sensitivity Analyses: Association between Elderly Solo Household Rate and Infusion Therapy Utilization</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Analysis</strong></th>
<th style="text-align: right;"><strong>N</strong></th>
<th style="text-align: right;"><strong>β (95% CI)</strong></th>
<th style="text-align: right;"><strong><em>p</em></strong></th>
<th style="text-align: right;"><strong>R²</strong></th>
<th style="text-align: left;"><strong>Outliers Excluded</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Base model</strong></td>
<td style="text-align: right;">47</td>
<td style="text-align: right;"><strong>723.37 (376.52, 1,070.21)</strong></td>
<td style="text-align: right;"><strong>0.0001</strong></td>
<td style="text-align: right;"><strong>0.282</strong></td>
<td style="text-align: left;">–</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Outlier exclusion</strong></td>
<td style="text-align: right;">45</td>
<td style="text-align: right;"><strong>925.11 (574.13, 1,276.09)</strong></td>
<td style="text-align: right;"><strong>&lt;0.001</strong></td>
<td style="text-align: right;"><strong>0.384</strong></td>
<td style="text-align: left;">Hokkaido, Kochi</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Tokyo exclusion</strong></td>
<td style="text-align: right;">46</td>
<td style="text-align: right;"><strong>696.92 (345.80, 1,048.04)</strong></td>
<td style="text-align: right;"><strong>0.0002</strong></td>
<td style="text-align: right;"><strong>0.274</strong></td>
<td style="text-align: left;">Tokyo</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Stratified: High aging rate (≥31.3%)</strong></td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">264.50 (-93.82, 1,022.82)</td>
<td style="text-align: right;">0.458</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Stratified: Low aging rate (&lt;31.3%)</strong></td>
<td style="text-align: right;">23</td>
<td style="text-align: right;"><strong>1,254.30 (5.39, 2,503.21)</strong></td>
<td style="text-align: right;"><strong>0.049</strong></td>
<td style="text-align: right;"><strong>0.173</strong></td>
<td style="text-align: left;">–</td>
</tr>
</tbody>
</table>
<p><strong>Bold</strong> indicates <em>p</em> &lt; 0.05.</p>
<hr>
</section>
<section id="figure-legends" class="level2">
<h2 class="anchored" data-anchor-id="figure-legends">Figure Legends</h2>
<p><strong>Figure 1.</strong> Cook’s distance plot for outlier detection. Two prefectures (Hokkaido and Kochi) exceeded the conventional threshold of 4/N = 0.085, indicating potential outlier status.</p>
<p><strong>Figure 2.</strong> Scatter plot showing the association between elderly solo household rate (%) and infusion therapy utilization (per 100,000 population) across 47 Japanese prefectures, stratified by median aging rate. Solid line represents the linear regression fit within each stratum, with shaded area indicating 95% confidence interval. Top 5 and bottom 5 prefectures by infusion therapy rate are labeled.</p>
<p><strong>Figure 3.</strong> Scatter plot showing the association between elderly solo household rate (%) and infusion therapy utilization (per 100,000 population) across all 47 Japanese prefectures. Solid line represents the simple linear regression fit (β = 723.37, <em>p</em> = 0.0001, R² = 0.282), with shaded area indicating 95% confidence interval.</p>
</section>
<section id="figure-1" class="level2">
<h2 class="anchored" data-anchor-id="figure-1">Figure 1</h2>
<p><img src="../03_Analysis/results/sensitivity_analysis/cooks_distance.png" class="img-fluid"></p>
</section>
<section id="figure-2" class="level2">
<h2 class="anchored" data-anchor-id="figure-2">Figure 2</h2>
<p><img src="../03_Analysis/results/sensitivity_analysis/stratified_analysis.png" class="img-fluid"></p>
</section>
<section id="figure-3" class="level2">
<h2 class="anchored" data-anchor-id="figure-3">Figure 3</h2>
<p><img src="../03_Analysis/results/sensitivity_analysis/scatter_elderly_infusion_labeled.png" class="img-fluid"></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>